### ISSUE TITLE
Possible error in DigitalSignatureTest

### ISSUE THREAD

**Issue by HenriqueLin** [tecnico-sec/Java-Crypto-Functions#1]
Hello Professor, @miguelpardal 
I wonder if this line should use the function `verifyDigitalSignature` instead of `redigestDecipherCompare` just like line 65 in the same file.
https://github.com/tecnico-sec/Java-Crypto-Functions/blob/5a4d508959e4e398617f6098acafa37e69801c09/src/test/java/pt/tecnico/crypto/DigitalSignatureTest.java#L78

**Comment by miguelpardal** [comment]
Hi @HenriqueLin.
Thanks for bringing this up.
Indeed it should be the verifyDigitalSignature() method as in that test we are using the Signature object.
The code will still work with the other method, as they are functionally equivalent.
Thanks!
